[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
auto_detect_solc = false

remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@solmate/=lib/solmate/src/",
    "foundry-devops/=lib/foundry-devops/lib/" 
]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[profile.fs_permissions]
read = ["./broadcast", "./reports"]

[fuzz]
runs = 256 